name: grafana
base: core18
summary: feature rich metrics dashboard and graph editor
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Cloudwatch,
  Elasticsearch, Graphite, InfluxDB, OpenTSB, Prometheus, and Hosted Metrics.
confinement: strict

adopt-info: grafana

apps:
  grafana:
    command: 'bin/grafana.wrapper'
    plugs: [network-bind, network]
    daemon: simple

parts:
  snap-wrappers:
    plugin: dump
    source: bin
    organize:
      grafana.wrapper: bin/grafana.wrapper
  grafana:
    plugin: go
    source: https://github.com/grafana/grafana.git
    source-tag: v5.4.3
    go-channel: 1.11/stable
    go-importpath: github.com/grafana/grafana
    build-packages:
      - git
      - build-essential
    override-build: |
        cd ../go/src/github.com/grafana/grafana
        version="$(git describe --tags --always --dirty)"
        [ -n "$(echo $version | grep '-')" ] && grade=devel || grade=stable
        snapcraftctl set-version "$version"
        snapcraftctl set-grade "$grade"
        go run build.go setup
        go run build.go build
        mkdir $SNAPCRAFT_PART_INSTALL/bin $SNAPCRAFT_PART_INSTALL/conf
        cp -p $SNAPCRAFT_PART_INSTALL/../go/bin/grafana-server $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/conf/defaults.ini $SNAPCRAFT_PART_INSTALL/conf/
  grafana-ui:
    after: [grafana]
    plugin: nodejs
    source-type: git
    source: https://github.com/grafana/grafana.git
    source-tag: v5.4.3
    nodejs-package-manager: yarn
    override-build: |
      snapcraftctl build
      cp -rvf $SNAPCRAFT_PART_BUILD/public $SNAPCRAFT_PART_INSTALL/public
